### ISSUE TITLE
 Error 404: NOT_FOUND while deploying to Vercel

### ISSUE THREAD

**Issue by alokemajumder** [hoichoi-opensource/imageresizer#10]
I encountered an error while trying to deploy the project to Vercel. The deployment failed, and I received the following error message, while trying to upload the image and resize it .

`404: NOT_FOUND
Code: NOT_FOUND
ID: bom1::krfmm-1696231582630-9713fa1e91c3

`
Steps to Reproduce:

Pushed the latest changes to the GitHub repository.
Triggered a new deployment on Vercel.
Now go to the url and upload a image and then try to resize it .

**Comment by arp99** [comment]
Hi @alokemajumder I tried deploying to vercel a fork of the repi, directly without changing any configurations. I could successfully deploy it. https://imageresizer-inky.vercel.app/
I guess the issue is resolved and can be closed

**Comment by hoichoidev** [comment]
Hi @arp99 ,
Thanks for your help and effort. Unfortunately , the error is not in the deployment. Try uploading and resize an image on the frontend , say - https://imageresizer-inky.vercel.app/ and see you will encounter the error.

**Comment by alokemajumder** [comment]
@arp99 Hi, Please let us know if you would be interested to take this up . Thanks

**Comment by ItsRoy69** [comment]
Can work on this issue

**Comment by alokemajumder** [comment]
This is fixed now . Configuration changes done at vercel to fix the deployment issue.
