### ISSUE TITLE
[BUG 🐞] Node modules to be removed

### ISSUE THREAD

**Issue by warmachine028** [hoichoi-opensource/imageresizer#13]
- Node modules must not be uploaded to version control
- It must be added to .gitignore file to untrack it

Assign me this issue to remove node_modules directory

**Comment by alokemajumder** [comment]
This makes sense and assigned. Thanks

**Comment by warmachine028** [comment]
solving this issue now

**Comment by hoichoidev** [comment]
Nice, can you please update the readme with required node modules to be installed in order to successfully run this.

Thanks

**Comment by warmachine028** [comment]
I believe ```npm install``` is sufficient given that you already have package.json present in the directory.

**Comment by alokemajumder** [comment]
Great job, @warmachine028 . Am closing this. Check if you can fix the other open issues. Best,
