### ISSUE TITLE
UI/UX Improvements Needed for Image Upload and Resize Feature

### ISSUE THREAD

**Issue by hoichoidev** [hoichoi-opensource/imageresizer#9]
Issue:
The current UI/UX design for the image upload and resize feature on the frontend lacks intuitiveness and clarity. Users have reported difficulties in understanding the process and have experienced inconsistencies in the resizing functionality.

Steps to Reproduce:

Navigate to the image upload section.
Try uploading an image.
Attempt to resize the uploaded image.
Expected Behavior:

The image upload button should be clearly labeled and easily accessible.
Upon uploading, users should receive feedback indicating a successful upload.
The resize feature should provide clear handles or markers to adjust the image dimensions.
The final resized image should maintain its aspect ratio and quality.
Actual Behavior:

The upload button is not prominently displayed.
No feedback is provided after image upload.
Resizing handles are not intuitive, leading to distorted images.
The resized image sometimes loses quality.
Suggested Improvements:

Redesign the image upload button to make it more prominent and add a tooltip or label.
Provide a success notification or visual cue after a successful image upload.
Improve the resizing handles to ensure they are user-friendly and maintain the image's aspect ratio.
Ensure the image quality remains consistent after resizing.

**Comment by malavshah9** [comment]
@hoichoidev Do we have mockup or wireframe for this? I would love to work on this if I get better picture on what type of UI we want here.

**Comment by hoichoidev** [comment]
> @hoichoidev Do we have mockup or wireframe for this? I would love to work on this if I get better picture on what type of UI we want here.

Hi, @malavshah9 Thanks a lot for your interest. We would love to work together on this. Allow us some time to get back you with more information as this is in very early stage and the entire focus was on adding the features. 

Best

**Comment by RaunakMandal** [comment]
@hoichoidev looking forward to your inputs.

**Comment by sayakongit** [comment]
@hoichoidev Can you assign this to me? I have some idea to improve the UI/UX of the site.

**Comment by hoichoidev** [comment]
Hi All,

Thanks a lot for your interest to. be part of this . Requesting all to check the following discussion where we listed a basic design wireframe . Let's discuss there and finalise the same . Lets keep this place to handle issues only. 

#11 

Best

**Comment by sarkartanmay393** [comment]
@hoichoidev I would like to give it a simple, elegant look. If this issue needs to be fixed, I'd love to be here in Hoichoi repos.
